<a href="https://colab.research.google.com/github/prakhark877/AI-Mafia---Machine-Learning/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [3]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10

In [4]:
a = np.zeros(10)

#### 4.  How to find the memory size of any array

In [7]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
a.size

12

#### 5.  How to get the documentation of the numpy add function from the command line?

In [8]:
print(np.info(np. add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [10]:
a = np.zeros(10)
a[4] = 1

#### 7.  Create a vector with values ranging from 10 to 49

In [11]:
a = np.arange(10,49)

#### 8.  Reverse a vector (first element becomes last)

In [20]:
a = np.array([1,2,3,4,5])
a = np.flip(a)
print(a)

[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [28]:
import numpy as np
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]



#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [59]:
a = np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [56]:
a = np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [44]:
a = np.random.random((3,3,3))
print(a)

[[[0.30485138 0.64368159 0.27736207]
  [0.83892636 0.86025493 0.56100303]
  [0.72141552 0.78893239 0.51669369]]

 [[0.84629339 0.94227185 0.54982114]
  [0.24491001 0.23213725 0.19522829]
  [0.85852432 0.32241894 0.70973409]]

 [[0.1654348  0.54738692 0.75870845]
  [0.92362981 0.70424576 0.34415544]
  [0.11122265 0.2913034  0.40885602]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [51]:
a = np.random.random((10,10))
print(a)
print(a.min())
print(a.max())

[[0.3648688  0.57563585 0.04719094 0.2234423  0.9890376  0.08612027
  0.97975549 0.81379926 0.7964416  0.99659184]
 [0.83775136 0.73242701 0.60731576 0.06532572 0.464555   0.16207684
  0.7777215  0.53773076 0.94064514 0.11252189]
 [0.33452527 0.68169656 0.72930033 0.5834332  0.05378886 0.86150956
  0.91026199 0.96350862 0.76083805 0.74685765]
 [0.39467132 0.97335563 0.33257075 0.03718426 0.60628499 0.88006479
  0.68101125 0.51879964 0.45746703 0.8331602 ]
 [0.82990387 0.87037816 0.75191881 0.68183982 0.38150383 0.20767887
  0.87165104 0.1876883  0.6120906  0.94153747]
 [0.05522026 0.14064753 0.37183854 0.328054   0.02210571 0.48928194
  0.88137009 0.21499627 0.31259099 0.50099942]
 [0.46681951 0.89599171 0.03081541 0.80381522 0.83036406 0.59818932
  0.92670077 0.21142696 0.87757083 0.26630925]
 [0.00640157 0.82199404 0.03303788 0.60193358 0.6309164  0.6721748
  0.4040606  0.07913423 0.23948205 0.48105739]
 [0.24807935 0.68708099 0.74586565 0.34219536 0.83279572 0.41672011
  0.60985637 

#### 14. Create a random vector of size 30 and find the mean value

In [60]:
a = np.random.random(30)
z = a.mean()
print(z)

0.4115748263383627


#### 15. Create a 2d array with 1 on the border and 0 inside

In [61]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [62]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [63]:


print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)



nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [68]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [67]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [65]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
